// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnZG7LnrOJTacI16xRvtx8qAgCh2DU8pM',
    appId: '1:843141863014:web:9b45d73d66ab542cc77fa7',
    messagingSenderId: '843141863014',
    projectId: 'email-authentication-aa377',
    authDomain: 'email-authentication-aa377.firebaseapp.com',
    storageBucket: 'email-authentication-aa377.appspot.com',
    measurementId: 'G-70Z2N6T2FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANC-isBBKc_2e_EU4g50dehoq8krKlxLw',
    appId: '1:843141863014:android:ec3fcbd5b91ffc12c77fa7',
    messagingSenderId: '843141863014',
    projectId: 'email-authentication-aa377',
    storageBucket: 'email-authentication-aa377.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnZG7LnrOJTacI16xRvtx8qAgCh2DU8pM',
    appId: '1:843141863014:web:1ca5f2ff4c4ea316c77fa7',
    messagingSenderId: '843141863014',
    projectId: 'email-authentication-aa377',
    authDomain: 'email-authentication-aa377.firebaseapp.com',
    storageBucket: 'email-authentication-aa377.appspot.com',
    measurementId: 'G-P5T86T1PD2',
  );
}
